Pin 2649 [FILTER – Erogatore] BFF GET /agreements/eservices
pagopa/interop-be-backend-for-frontend pull request #101
Opened 2023-02-14 11:42 UTC by nttdata-rtorsoli

2023-02-16 09:14 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/AgreementsApiServiceImpl.scala
> +    logger.info(s"Retrieving eservices from agreement filtered by eservice name $q, offset $offset, limit $limit")
```suggestion
    logger.info(s"Retrieving producer eservices from agreement filtered by eservice name $q, offset $offset, limit $limit")
```

2023-02-16 09:14 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/AgreementProcessService.scala
> +    offset: Int = 0
let's avoid default values if not strictly required
```suggestion
    offset: Int
```

2023-02-16 09:14 UTC, galales commented on src/main/resources/interface-specification.yml
> +              description: Time interval in milliseconds. Allowed requests will be constantly replenished during the interval. At the end of the interval the max allowed requests will be available
Unused status
```suggestion
```

2023-02-16 16:16 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/AgreementsApiServiceImpl.scala
> +  }
ditto

2023-02-16 16:19 UTC, TonioGela requested changes

2023-02-16 16:19 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/AgreementsApiServiceImpl.scala
> +  }
[ditto](https://github.com/pagopa/interop-be-backend-for-frontend/pull/105#discussion_r1108706548)

2023-02-20 07:55 UTC, TonioGela approved these changes

2023-02-20 14:07 UTC, galales approved these changes

2023-02-20 14:18 UTC, merged