Pin 2650 [FILTER – Fruitore] BFF GET /agreements/eservices
pagopa/interop-be-backend-for-frontend pull request #106
Opened 2023-02-15 10:02 UTC by nttdata-rtorsoli

[FILTER – Fruitore] BFF GET /agreements/eservices

2023-02-16 09:15 UTC, galales commented on src/main/resources/interface-specification.yml
> +              description: Time interval in milliseconds. Allowed requests will be constantly replenished during the interval. At the end of the interval the max allowed requests will be available
Unused status
```suggestion
```

2023-02-16 16:25 UTC, TonioGela requested changes

2023-02-16 16:25 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/AgreementsApiServiceImpl.scala
> +    }
Same comment as in the other cases

2023-02-20 07:56 UTC, TonioGela approved these changes

2023-02-20 14:07 UTC, galales approved these changes

2023-02-20 14:27 UTC, merged