[Pin 2769] Add descriptorId to the response of POST /eservices/.../clone
pagopa/interop-be-backend-for-frontend pull request #107
Opened 2023-02-15 11:27 UTC by AsterITA

2023-02-16 09:25 UTC, galales commented on src/main/resources/interface-specification.yml
> +    CreatedResourceWithDescriptorId:
```suggestion
    CreatedEServiceDescriptor:
```

2023-02-16 09:25 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/error/Handlers.scala
> +    case Failure(err: NoDescriptorInEservice)                   => notFound(err, logMessage)
In this case we can remove the handling of this exception.
This is something that should never occur, it is ok if the servire returns a 500 (so we can be notified)

2023-02-16 16:33 UTC, TonioGela requested changes

2023-02-16 16:33 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/error/Handlers.scala
> +    case Failure(err: NoDescriptorInEservice)                   => notFound(err, logMessage)
+1

2023-02-17 09:21 UTC, TonioGela approved these changes

2023-02-17 17:20 UTC, beetlecrunch approved these changes

2023-02-20 08:45 UTC, galales approved these changes

2023-02-20 10:31 UTC, merged