PIN-1373 purpose-process POST /purposes/{purposeId}/versions/{versionId}/archive
pagopa/interop-be-backend-for-frontend pull request #121
Opened 2023-02-23 14:05 UTC by nttdata-rtorsoli

2023-02-24 14:51 UTC, TonioGela approved these changes

2023-02-24 16:22 UTC, beetlecrunch approved these changes

2023-02-27 08:27 UTC, galales requested changes

2023-02-27 08:27 UTC, galales commented on src/main/resources/interface-specification.yml
> +                $ref: '#/components/schemas/CompactPurposeVersion'
let's pause this PR until [this one](https://github.com/pagopa/interop-be-backend-for-frontend/pull/116/files#diff-17a3d713b849787a0ed57552f2b367a47eedf4cef81a6ba025d0060ac107d213R4041) has been marged, so you can return the same model

2023-02-27 15:04 UTC, galales approved these changes

2023-02-27 15:50 UTC, merged