PIN-1368 purpose-process POST /purposes/{purposeId}/versions/{versionId}/update/waitingForApproval
pagopa/interop-be-backend-for-frontend pull request #122
Opened 2023-02-23 15:00 UTC by nttdata-rtorsoli

2023-02-24 10:21 UTC, galales requested changes

2023-02-24 10:21 UTC, galales commented on src/main/resources/interface-specification.yml
> +              $ref: '#/components/schemas/WaitingForApprovalPurposeVersionUpdateContentSeed'
here just the ids are enough, see `CreatedEServiceDescriptor`

2023-02-24 14:03 UTC, galales commented on src/main/resources/interface-specification.yml
> +                $ref: '#/components/schemas/CreatedResource'
same considerations [here](https://github.com/pagopa/interop-be-backend-for-frontend/pull/116#discussion_r1117039935)

2023-02-24 14:21 UTC, TonioGela approved these changes

2023-02-24 16:39 UTC, beetlecrunch approved these changes

2023-02-27 15:04 UTC, galales approved these changes

2023-02-27 15:44 UTC, merged