[PIN-2832] Migration of DELETE /eservices/.../{descriptorId} and DELETE /eservic…
pagopa/interop-be-backend-for-frontend pull request #126
Opened 2023-02-24 16:13 UTC by bloodsky

…es/{eServiceId}

2023-02-24 16:25 UTC, TonioGela requested changes

2023-02-24 16:25 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/impl/CatalogProcessServiceImpl.scala
> +      invoker.invoke(request, s"")
👀

2023-02-27 09:23 UTC, galales approved these changes

2023-02-27 09:23 UTC, galales commented on src/main/resources/interface-specification.yml
> +            type: string
```suggestion
            type: string
            format: uuid
```

2023-02-27 09:23 UTC, galales commented on src/main/resources/interface-specification.yml
> +            type: string
```suggestion
            type: string
            format: uuid
```

2023-02-27 14:04 UTC, TonioGela approved these changes

2023-02-27 14:20 UTC, merged