PIN-1326 authorization-process DELETE /clients/{clientId}
pagopa/interop-be-backend-for-frontend pull request #127
Opened 2023-02-28 10:08 UTC by nttdata-rtorsoli

2023-02-28 11:48 UTC, galales requested changes

2023-02-28 11:48 UTC, galales commented on project/Dependencies.scala
> +      pagopa.authorizationProcessClient    % Compile,
formatting 🙏

2023-02-28 11:48 UTC, galales commented on project/Versions.scala
> +  lazy val authorizationProcessVersion    = "1.0.x-SNAPSHOT"
formatting 🙏

2023-02-28 11:48 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/AuthorizationApiServiceImpl.scala
> +  override def deleteClient(
it is not wrong to put this here, but this class is focused on actually allow or deny access to the platform, which is a bit sensitive and I would keep it isolated.

May I ask you to move this (and future) authorization process endpoints to a different class? For example to a new class named `ClientsApiServiceImpl`

2023-02-28 11:48 UTC, galales commented on src/main/resources/interface-specification.yml
> +        - authorization
this would change to
```suggestion
        - clients
```
based on the other comment

2023-02-28 17:03 UTC, galales requested changes
probably my previous comment was not crystal clear, to avoid confusion I highlighted the changes I meant

2023-02-28 17:03 UTC, galales commented on project/Dependencies.scala
> +    lazy val authProcessClient =
```suggestion
    lazy val authorizationProcessClient =
```

2023-02-28 17:03 UTC, galales commented on project/Versions.scala
> +  lazy val authProcessVersion       = "1.0.x-SNAPSHOT"
```suggestion
  lazy val authorizationProcessVersion       = "1.0.x-SNAPSHOT"
```

2023-02-28 17:03 UTC, galales commented on src/main/resources/application.conf
> +    client-process = ${CLIENT_PROCESS_URL}
this was fine because it refers to the actual authorization process service
```suggestion
    authorization-process = ${AUTHORIZATION_PROCESS_URL}
```

2023-02-28 17:03 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/common/system/ApplicationConfiguration.scala
> +  val clientProcessURL: String     = config.getString("backend-for-frontend.services.client-process")
```suggestion
  val authorizationProcessURL: String     = config.getString("backend-for-frontend.services.authorization-process")
```

2023-02-28 17:03 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/server/impl/dependencies/Dependencies.scala
> +    val clientProcess: ClientProcessService                   =
```suggestion
    val authorizationProcess: AuthorizationProcessService                   =
```

2023-02-28 17:03 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/ClientProcessService.scala
> +trait ClientProcessService {
this was fine because it refers to the actual authorization process service, you can delete this file and keep the `AuthorizationProcessService` you already created

2023-02-28 17:03 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/impl/ClientProcessServiceImpl.scala
> +class ClientProcessServiceImpl(authorizationProcessUrl: String, blockingEc: ExecutionContextExecutor)(implicit
same, you can delete this file and keep the existing `AuthorizationProcessServiceImpl`

2023-02-28 17:03 UTC, galales commented on src/test/resources/application-test.conf
> +    client-process = "CLIENT_PROCESS_URL"
```suggestion
    authorization-process = "AUTHORIZATION_PROCESS_URL"
```

2023-02-28 17:03 UTC, galales commented on src/test/scala/it/pagopa/interop/backendforfrontend/ErrorHandlerSpec.scala
> +    "handle Client Process error" in {
```suggestion
    "handle Authorization Process error" in {
```

2023-02-28 17:03 UTC, galales commented on src/test/scala/it/pagopa/interop/backendforfrontend/SpecHelper.scala
> +  val mockClientProcess: ClientProcessService          = mock[ClientProcessService]
```suggestion
  val mockAuthorizationProcess: AuthorizationProcessService          = mock[AuthorizationProcessService]
```

2023-02-28 17:03 UTC, galales commented on src/test/scala/it/pagopa/interop/backendforfrontend/ErrorHandlerSpec.scala
> +import it.pagopa.interop.authorizationprocess.client.invoker.{ApiError => ClientProcessError}
```suggestion
import it.pagopa.interop.authorizationprocess.client.invoker.{ApiError => AuthorizationProcessError}
```

2023-03-01 09:34 UTC, galales approved these changes

2023-03-01 11:48 UTC, beetlecrunch approved these changes

2023-03-01 13:35 UTC, merged