PIN-1325 authorization-process POST /clientsApi
pagopa/interop-be-backend-for-frontend pull request #148
Opened 2023-03-13 14:54 UTC by nttdata-rtorsoli

2023-03-14 08:24 UTC, galales requested changes

2023-03-14 08:24 UTC, galales commented on src/main/resources/interface-specification.yml
> +  /clients/api:
same considerations [here](https://github.com/pagopa/interop-be-backend-for-frontend/pull/147#discussion_r1135158659)

2023-03-14 08:24 UTC, galales commented on src/main/resources/interface-specification.yml
> +          maxLength: 250
Constraints are on the process

```suggestion
        description:
          type: string
```

2023-03-14 08:24 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/impl/AuthorizationProcessServiceImpl.scala
> +      invoker.invoke(request, s"create api client with name ${clientSeed.name}")
```suggestion
      invoker.invoke(request, s"Create api client with name ${clientSeed.name}")
```

2023-03-14 14:18 UTC, galales approved these changes

2023-03-15 09:35 UTC, beetlecrunch approved these changes

2023-03-15 16:42 UTC, merged