PIN-3149 Status 404 su GET /clients subito dopo cancellazione di un client
pagopa/interop-be-backend-for-frontend pull request #160
Opened 2023-03-24 13:39 UTC by nttdata-rtorsoli

2023-03-27 09:21 UTC, galales requested changes
the new authorization-process endpoint should not be invoked as a separated BFF endpoint, but in the existing `/clients` in the BFF

2023-03-27 13:31 UTC, galales commented on src/main/resources/interface-specification.yml
> +            $ref: '#/components/schemas/CompactClientWithKeys'
we should keep the previous definition

2023-03-27 13:58 UTC, TonioGela commented
Is this PR actual? I do see some CI errors and unanswered discussions

2023-03-30 09:12 UTC, galales commented on src/main/resources/interface-specification.yml
> +        - name
no more required 
```suggestion
```

2023-03-30 09:12 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/package.scala
> +    jsonFormat2(CompactKey)
No more required
```suggestion
```

2023-03-30 09:12 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/types/AuthorizationProcessServiceTypes.scala
> +  }
No more required
```suggestion
```

2023-03-30 09:12 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/types/AuthorizationProcessServiceTypes.scala
> +  implicit class ClientEntryKeyProcessConverter(private val c: AuthorizationProcess.ClientWithKeys) extends AnyVal {
can you please move it back to minimize code changes?

2023-03-30 09:12 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/package.scala
> +    jsonFormat2(CompactClients)
can you please move it back to minimize code changes?

2023-03-30 09:12 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/ClientsApiMarshallerImpl.scala
> +    sprayJsonMarshaller[CompactClients]
can you please move it back to minimize code changes?

2023-03-30 14:44 UTC, TonioGela approved these changes

2023-03-30 15:15 UTC, nttdata-rtorsoli commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/types/AuthorizationProcessServiceTypes.scala
> +  }
implicit class CompactClientConverter(private val c: AuthorizationProcess.Client) was a duplicate

2023-03-30 15:33 UTC, galales approved these changes

2023-03-30 15:38 UTC, merged