PIN-3022 [BE] Nel listing delle finalità lato erogatore devono essere escluse quelle in stato DRAFT
pagopa/interop-be-backend-for-frontend pull request #170
Opened 2023-04-13 11:28 UTC by nttdata-rtorsoli

2023-04-14 07:47 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/PurposesApiServiceImpl.scala
> +        eServicesUUIDs <- parseArrayParameters(eServicesIds).distinct.traverse(_.toFutureUUID)
We should really write an util function in commons for this use case :\

2023-04-14 12:53 UTC, galales requested changes

2023-04-14 12:53 UTC, galales commented on src/main/resources/interface-specification.yml
> +            type: boolean
This should not be exposed to the frontend.
The flag is set by the endpoint when calling the process
```suggestion
```

2023-04-14 12:53 UTC, galales commented on src/main/resources/interface-specification.yml
> +            type: boolean
Same
```suggestion
```

2023-04-14 12:53 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/PurposesApiServiceImpl.scala
> +          excludeDraft = excludeDraft,
```suggestion
          excludeDraft = false.some,
```

2023-04-14 12:53 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/PurposesApiServiceImpl.scala
> +          excludeDraft = excludeDraft,
```suggestion
          excludeDraft = true.some,
```

2023-04-14 12:53 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/PurposesApiServiceImpl.scala
> +  override def getProducerPurposes(
the two endpoints are identical, let's write a single parametric function called by both and remove code duplication

2023-04-27 07:26 UTC, galales approved these changes

2023-04-27 08:54 UTC, beetlecrunch approved these changes

2023-04-27 13:02 UTC, nttdata-rtorsoli commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/PurposesApiServiceImpl.scala
> +        eServicesUUIDs <- parseArrayParameters(eServicesIds).distinct.traverse(_.toFutureUUID)
We can do that in other specific story

2023-04-27 13:14 UTC, merged