PIN-3576 Added eserviceId and consumerId to PurposeUpdateContent
pagopa/interop-be-backend-for-frontend pull request #204
Opened 2023-07-17 11:58 UTC by nttdata-rtorsoli

2023-07-18 13:10 UTC, beetlecrunch commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/PurposesApiServiceImpl.scala
> +      _              <- tenantProcessService.getTenant(purposeUpdateContent.consumerId)
[Same](https://github.com/pagopa/interop-be-purpose-process/pull/169/files#r1266751056)

2023-07-18 13:15 UTC, beetlecrunch commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/PurposesApiServiceImpl.scala
> +      _              <- tenantProcessService.getTenant(purposeUpdateContent.consumerId)
These are already checked at the process level.
We can remove them.

2023-07-18 13:18 UTC, beetlecrunch approved these changes

2023-07-26 08:13 UTC, TonioGela approved these changes

2023-07-26 09:46 UTC, galales requested changes

2023-07-26 09:46 UTC, galales commented on src/main/resources/interface-specification.yml
> +        consumerId:
as per other PRs, `consumerId` should not be changed

2023-07-26 12:46 UTC, galales approved these changes

2023-07-26 12:46 UTC, galales commented on src/main/resources/interface-specification.yml
> +        - consumerId
```suggestion
```

2023-07-28 09:26 UTC, merged