PIN-3668 Corrected parameters JWT for SAML validation
pagopa/interop-be-backend-for-frontend pull request #207
Opened 2023-07-25 14:01 UTC by nttdata-rtorsoli

2023-07-25 14:50 UTC, galales requested changes

2023-07-25 14:50 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/Utils.scala
> -      USER_ROLES            -> SUPPORT_ROLE,
I double checked in commons, this field is required to identify the user role inside interop and must be kept

2023-07-25 14:50 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/Utils.scala
> +  val PAGOPA = "PagoPA"
This is the name currently stored for the tenant
```suggestion
  val PAGOPA = "PagoPA S.p.A."
```

2023-07-25 15:19 UTC, galales approved these changes
👍 
probably it needs a code format

2023-07-26 07:46 UTC, beetlecrunch approved these changes

2023-07-26 07:52 UTC, merged