PIN-4060: updated Selfcare models with new api
pagopa/interop-be-backend-for-frontend pull request #239
Opened 2023-10-18 09:24 UTC by AsterITA

2023-10-19 12:27 UTC, galales requested changes

2023-10-19 12:27 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/types/SelfcareClientTypes.scala
> +        parent           <- i.rootParent.map(_.description)
`parent` is optional, but used in this for comprehension it is considered as required

2023-10-20 09:06 UTC, galales approved these changes

2023-10-23 13:00 UTC, beetlecrunch approved these changes

2023-10-24 08:09 UTC, merged