Pin 4923: getPresignedUrl
pagopa/interop-be-backend-for-frontend pull request #279
Opened 2024-06-03 15:51 UTC by AsterITA

[TO merge after #277 ]

2024-06-04 13:45 UTC, galales requested changes

2024-06-04 13:45 UTC, galales commented on src/main/resources/interface-specification.yml
> +      operationId: getPresignedUrl
```suggestion
      operationId: getImportEservicePresignedUrl
```

2024-06-04 13:45 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/EServicesApiServiceImpl.scala
> +        ApplicationConfiguration.importEServicePath
IMO the path should also contain the tenant id, it allows:
- easily debugging on users' reports
- implementing authorization rules

2024-06-04 13:45 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/common/system/ApplicationConfiguration.scala
> +  val importEServiceContainer: String     = config.getString("backend-for-frontend.storage.import-eservice.container")
```suggestion
  val importEServiceContainer: String    = config.getString("backend-for-frontend.storage.import-eservice.container")
```

2024-06-04 13:45 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/common/system/ApplicationConfiguration.scala
these new configurations should be added also to `application.conf` and `application-standalone.conf` files.

May I ask to open an IFST task to add these in the deployment?

2024-06-04 13:45 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/EServicesApiServiceImpl.scala
> +      handleError("Error getting presigned url", headers) orElse { case Success(resource) =>
```suggestion
      handleError("Error getting eservice import presigned url", headers) orElse { case Success(resource) =>
```

2024-06-04 13:45 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/EServicesApiServiceImpl.scala
> +        ApplicationConfiguration.importEServicePath
also, if I recall correctly, the presigned url request should also contain the file name

2024-06-04 14:49 UTC, AsterITA commented on src/main/scala/it/pagopa/interop/backendforfrontend/common/system/ApplicationConfiguration.scala
Task created: https://pagopa.atlassian.net/browse/PIN-4955

2024-06-06 06:43 UTC, galales reviewed
just one more point 🙏

2024-06-06 06:43 UTC, galales commented on src/main/resources/interface-specification.yml
> +  /import/eservices/{tenantId}/presignedUrl:
tenantId should be taken from the jwt, if we leave the caller to pass the value we lose the authorization check
```suggestion
  /import/eservices/presignedUrl:
```

2024-06-06 10:22 UTC, galales approved these changes

2024-06-19 10:23 UTC, beetlecrunch approved these changes

2024-06-19 10:40 UTC, merged