PIN 1862
pagopa/interop-be-backend-for-frontend pull request #37
Opened 2022-09-27 15:56 UTC by TonioGela

- Refactoring dependencies part 1
- Refactoring dependencies
- Adding the skeleton of the calls to perform
- repacking some custom claim
- Fixed the succeed test

2022-09-27 15:58 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/AuthorizationApiServiceImpl.scala
> +  private val SELFCARE_ID_CLAIM = "selfcare_id"
It needs to be added [with this PR](https://github.com/pagopa/interop-commons/pull/200) to commons too and to use its getter

2022-09-27 15:59 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/AuthorizationApiServiceImpl.scala
> +      .selfcareUpsertTenant(partyInstitution.origin, partyInstitution.externalId)(partyInstitution.id)
I'm totally not sure about this repacking. `partyInstitution` has both origin and originId, so I'm not sure about which to use. I'll ask for details.

2022-09-27 16:48 UTC, TonioGela commented on src/test/scala/it/pagopa/interop/backendforfrontend/AuthorizationApiServiceSpec.scala
>      "succeed" in {
We need an end to end test for this api that sends the claims encoded through tcp to be sure we won't have problems again

2022-09-30 16:45 UTC, galales requested changes

2022-09-30 16:45 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/AuthorizationApiServiceImpl.scala
>    private def getOrganizationId(claims: JWTClaimsSet): Try[UUID] = for {
```suggestion
  private def getSelfcareId(claims: JWTClaimsSet): Try[String] = for {
```
`selfcareId` is a `String` 🥲

2022-09-30 16:45 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/server/impl/dependencies/Dependencies.scala
> +    val tenantProcess: TenantProcessService                   = new TenantProcessServiceImpl(null, null)
⚠️ wut?

2022-09-30 16:45 UTC, galales commented on src/test/scala/it/pagopa/interop/backendforfrontend/AuthorizationApiServiceSpec.scala
> +      val selfcareId: UUID = UUID.randomUUID()
why not defining this directly as a String instead of using `toString` everywhere?
Because, you know, this is a `String` 🥲

2022-09-30 16:45 UTC, galales commented on src/test/scala/it/pagopa/interop/backendforfrontend/AuthorizationApiServiceSpec.scala
> +      val selfcareId: UUID = UUID.randomUUID()
same

2022-10-05 08:36 UTC, beetlecrunch approved these changes

2022-10-05 08:37 UTC, galales approved these changes

2022-10-05 09:41 UTC, merged