[PIN-1290] Adding route POST /eservices for catalog-process
pagopa/interop-be-backend-for-frontend pull request #82
Opened 2023-01-27 15:23 UTC by bloodsky

2023-01-30 08:29 UTC, TonioGela requested changes

2023-01-30 08:29 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/CatalogApiServiceImpl.scala
> +    } yield converted
I would instead prefer something like this, as the for comprehension is not strictly necessary in this case:

```suggestion
    def result: Future[OldEService] = catalogProcess.createEService(eServiceSeed.toProcess)(contexts).map(_.toApi)
```

or at least to move the mapping in the yield like: 

```suggestion
    val result: Future[OldEService] = for {
      response <- catalogProcess.createEService(eServiceSeed.toProcess)(contexts)
    } yield response.toApi
```

as it won't be sent two times to two different execution contexts

2023-01-30 08:29 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/CatalogProcessService.scala
>    def getEServices(
can you add a \n?

2023-01-30 08:29 UTC, TonioGela commented on src/main/scala/it/pagopa/interop/backendforfrontend/service/types/CatalogProcessServiceTypes.scala
> +  implicit class CatalogOldAttributesConverter(private val coas: CatalogProcessOldAttributes)         extends AnyVal {
There's a lack of \n between classes here, I won't mark it all

2023-01-30 09:24 UTC, galales requested changes

2023-01-30 09:24 UTC, galales commented on src/main/resources/interface-specification.yml
> +      summary: Create a new e-service
Let's use the same naming everywhere
```suggestion
      summary: Create a new EService
```

2023-01-30 09:24 UTC, galales commented on src/main/resources/interface-specification.yml
> +        description: An E-Service seed
same
```suggestion
        description: An EService seed
```

2023-01-30 09:24 UTC, galales commented on src/main/resources/interface-specification.yml
> +                $ref: '#/components/schemas/Problem'
rate limiting headers needed

2023-01-30 09:24 UTC, galales commented on src/main/resources/interface-specification.yml
> +          maxLength: 250
constraints should not be in the BFF, we agreed to centralize them only on process services
```suggestion
        description:
          type: string
```

2023-01-30 09:24 UTC, galales commented on src/main/resources/interface-specification.yml
> +                $ref: '#/components/schemas/OldEService'
(confirmed by @Carminepo2 ) we need to return just the id of the new eservice, you can use the `CreatedResource` model

Btw, models named `Old*` are just intended as a temporary measure in the catalog process.
Names in the BFF should not be named with `Old` prefix (and these specific models are not needed here)

2023-01-30 09:24 UTC, galales commented on src/main/scala/it/pagopa/interop/backendforfrontend/api/impl/CatalogApiServiceImpl.scala
> +final case class CatalogApiServiceImpl(catalogProcess: CatalogProcessService)(implicit ec: ExecutionContext)
in the BFF already exists the `EServicesApiServiceImpl`, you should move this logic there

2023-01-30 09:24 UTC, galales commented on src/main/resources/interface-specification.yml
> +        - catalog
```suggestion
        - eservices
```

2023-01-30 09:24 UTC, galales commented on src/main/resources/interface-specification.yml
> +            $ref: '#/components/schemas/EServiceDescriptor'
you probably do not need these models

2023-01-30 13:56 UTC, galales approved these changes
🚀 
Just remember that [this](https://github.com/pagopa/interop-be-backend-for-frontend/pull/82/files#diff-b9cc9357f75e7dd8cdee77916533ecee2bab1e58a2aa0c2b823e361346eeaa22R23) will slightly change once the corresponding endpoint in the catalog process will be updated

2023-01-31 08:20 UTC, TonioGela approved these changes

2023-01-31 09:25 UTC, TonioGela approved these changes

2023-01-31 10:08 UTC, galales approved these changes

2023-01-31 10:08 UTC, merged